site_name: Hackerspace.gent documentation
nav:
- Home: index.md
- Newline: newline.md
- Infra: infra.md
- Contact: comms.md
theme:
  #name: readthedocs
  name: material
repo_url: https://github.com/0x20/docs
edit_uri: blob/main/docs/
