site_name: Hackerspace.gent documentation
site_url: https://docs.hackerspace.gent

repo_url: https://github.com/0x20/docs
repo_name: 0x20/docs
edit_uri: blob/main/docs/

nav:
- Home: index.md
- Infrastructure:
  - infra/index.md
  - Bar: infra/bar.md
  - Door access: infra/door_access.md
  - 3D Printer: infra/printer3d.md
  - 2D Printer: infra/printer2d.md
  - Electricity: infra/electricity.md
  - Garbage: infra/garbage.md
  - CNC: infra/cnc.md
  - Drinks: infra/drinks.md
  - Flappers doorbell: infra/flappers_doorbell.md
  - Stadsmakers: infra/stadsmakers.md
- Newline: newline.md
- Contact: comms.md
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - content.action.edit
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.top
    - navigation.footer
    - navigation.expand
    - navigation.indexes
    - search.suggest
    - search.share
plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
  - git-committers:
      repository: 0x20/docs
      branch: main
  - glightbox
extra:
  social:
    - icon: fontawesome/brands/mastodon
      link: https://chaos.social/@hsg
    - icon: fontawesome/brands/github
      link: https://github.com/0x20
    - icon: material/email
      link: https://discuss.hackerspaces.be/
    - icon: fontawesome/solid/location-dot
      link: https://www.openstreetmap.org/?mlat=51.074762&mlon=3.724422#map=18/51.074762/3.724422
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/hsghent
