site_name: Hackerspace.gent documentation
site_url: https://docs.hackerspace.gent

repo_url: https://github.com/0x20/docs
repo_name: 0x20/docs
edit_uri: blob/main/docs/

nav:
- Home: index.md
- Newline: newline.md
- Infra:
  - infra/index.md
  - Bar: infra/bar.md
  - Door access: infra/door_access.md
  - 3D Printer: infra/printer3d.md
  - 2D Printer: infra/printer2d.md
  - Drinks: infra/drinks.md
  - Flappers doorbell: infra/flappers_doorbell.md
  - Stadsmakers: infra/stadsmakers.md
- Contact: comms.md
theme:
  #name: readthedocs
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - content.action.edit
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.top
    - navigation.footer
    - navigation.expand
    - navigation.indexes
    - search.suggest
    - search.share
plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
  - git-committers:
      repository: 0x20/docs
      branch: main
